apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: doggy-gateway
  endpoints:
    - port: "8000"
      path: /v1/metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-alerts
  namespace: {{ .Release.Namespace }}
spec:
  groups:
    - name: doggy-alerts
      rules:
        {{- range .Values.prometheusRules }}
        - alert: {{ .alert }}
          expr: {{ .expr }}
          for: {{ .for }}
          labels:
            {{- toYaml .labels | nindent 12 }}
          annotations:
            {{- toYaml .annotations | nindent 12 }}
        {{- end }}