apiVersion: v1
kind: Secret
metadata:
  name: doggy-db-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  write_url: "postgresql://doggy:${DB_PASSWORD}@pg-primary.doggy-data:5432/doggy"
  read_url: "postgresql://doggy:${DB_PASSWORD}@pg-replica.doggy-data:5432/doggy"
---
apiVersion: v1
kind: Secret
metadata:
  name: nim-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  api_key: "${NIM_API_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: doggy-api-keys
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  openai: "${DOGGY_OPENAI_API_KEY}"